server:
  port: 10010

spring:
  application:
    name: project-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yanqun/project_config.git
  rabbitmq:
    host: 192.168.2.129

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
