server:
  port: 9002

spring:
  application:
    name: project-recruit
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/myproject_recruit?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true