server:
  port: 9005

spring:
  application:
    name: project-article
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.128:3306/myproject_article?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 192.168.2.128
    port: 6379
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true